//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public int sno { get; set; }
        public Nullable<decimal> Account_No { get; set; }
        public string Mode { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public string Maturity_Date { get; set; }
        public Nullable<decimal> Maturity_Amount { get; set; }
        public string Start_Date { get; set; }
        public string Won { get; set; }
    }
}
